type: sglang
image: lmsysorg/sglang:latest
checkpoint_path: ???
served_model_name: ???
port: 8000
tensor_parallel_size: 8
data_parallel_size: 1
extra_args: ""
env_vars: {} # {name: value} dict

endpoints:
  chat: /v1/chat/completions
  completions: /v1/completions
  health: /health

command: python3 -m sglang.launch_server
  --model-path /checkpoint
  --host 0.0.0.0
  --port ${deployment.port}
  --served-model-name ${deployment.served_model_name}
  --tp ${deployment.tensor_parallel_size}
  --dp ${deployment.data_parallel_size}
  ${deployment.extra_args}
