[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "nemo-evaluator"
description = "Common utilities for NVIDIA evaluation frameworks"
dynamic = ["version"]
dependencies = [
    "flask",
    "jinja2",
    "psutil",
    "pydantic",
    "pydantic-core>=2.17",
    "requests",
    "structlog",
    "typing-extensions>=4.0.0",
    "psutil",
    "pyyaml",
    "werkzeug",
    "yq",
]
requires-python = ">=3.9"
readme = "README.md"
license = {file = "LICENSE"}

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-subtests",
    "pytest-httpserver",
]

docs = [
    "sphinx",
    "sphinx-autobuild",  # For live doc serving while editing docs
    "sphinx-autodoc2",  # For documenting Python API
    "sphinx-copybutton",  # Adds a copy button for code blocks
    "myst_parser",  # For our markdown docs
    "nvidia-sphinx-theme",  # Our NVIDIA theme
]

all = [
    "nemo_evaluator[test,docs]"
]

[project.scripts]
nemo_evaluator_example = "nemo_evaluator.cli.example:main"
nemo-evaluator-example = "nemo_evaluator.cli.example:main"
eval-factory = "nemo_evaluator.core.entrypoint:run_eval"


[tool.setuptools.dynamic]
version = {file = "VERSION"}

[tool.setuptools.packages.find]
where = ["packages/nemo-evaluator/src"]
include = ["nemo_evaluator*"]


[tool.setuptools.package-data]
nemo_evaluator = ["resources/**/*"]
