[project]
name = "nemo-evaluator-launcher"
version = "0.0.0+dev.local"
description = "NeMo Evaluator Launcher - Public API"
requires-python = ">=3.10,<3.14"
readme = "README.md"
dependencies = [
  "hydra-core>=1.3.2,<2.0.0",
  "jinja2>=3.1.6,<4.0.0",
  "leptonai>=0.25.0",
  "pyyaml>=6.0.0",
  "requests>=2.32.4",
  "simple-parsing>=0.1.7,<0.2.0",
  "structlog>=25.4.0,<26.0.0",
  "tabulate>=0.9.0,<0.10.0",
  "tomli>=2.0.0,<3.0.0; python_version < '3.11'",
]

[project.optional-dependencies]
mlflow = ["mlflow>=2.8.0"]
wandb = ["wandb>=0.15.0"]
gsheets = ["gsheets>=0.1.0"]
exporters = ["mlflow", "wandb", "gsheets"]
all = ["mlflow", "wandb", "gsheets"]

[project.scripts]
nemo-evaluator-launcher = "nemo_evaluator_launcher.cli.main:main"
nv-eval = "nemo_evaluator_launcher.cli.main:main"

[dependency-groups]
dev = [
  "pre-commit>=4.2.0,<5",
  "python-semantic-release>=10.0.0,<11",
  "pytest>=8.0.0,<9.0.0",
  "pytest-network",
  "pytest-cov>=6.2.1,<7",
  "mypy>=1.17.1",
  "types-requests>=2.32.4.20250809",
  "types-pyyaml>=6.0.12.20250822",
]

[tool.hatch.build.targets.sdist]
include = [
  "src/nemo_evaluator_launcher",
  "src/nemo_evaluator_launcher/resources/**",
]

[tool.hatch.build.targets.wheel]
include = [
  "src/nemo_evaluator_launcher",
  "src/nemo_evaluator_launcher/resources/**",
]

[tool.hatch.build.targets.wheel.sources]
"src/nemo_evaluator_launcher" = "nemo_evaluator_launcher"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.isort]
known_first_party = [
  "nemo_evaluator_launcher",
  "nemo_evaluator_launcher_internal",
]
profile = "black"

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
commit_message = "chore(release): {version}"
commit_author = "eval-platform-ci <eval-platform-ci@nvidia.com>"
major_on_zero = false
allow_zero_version = true

[tool.semantic_release.branches.main]
match = "main"
prerelease = false
